version: '3.3'
services:
  zendtrack:
    image: chainsaw/zendtrack:latest
    command: zend
    environment:
      - rpcpassword
      - rpcuser
      - fqdn
      - stake
      - nodeid
    secrets:
     - id_rsa
    logging:
      driver: json-file
    deploy:
      resources:
        reservations:
          memory: 2969M
        limits:
          memory: 2969M
secrets:
  id_rsa:
    external: true